version: '3'

services: 
  service_db_clickhouse:
    container_name: service_db_clickhouse
     
    ports:
     - "8123:8123"
     - "9000:9000"
    links:
      - service_nats
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml
    image: clickhouse/clickhouse-server:23.4.2.11-alpine

  service_nats:
    container_name: service_nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - ./nats/nats.conf:/etc/nats.conf
    image: nats:2.9-alpine3.17